### PR TITLE
Bump static-eval version

### PR DESCRIPTION
**Pull request by archmoj**
Addressing https://npmjs.com/advisories/758 

@rreusser

### CODE REVIEW

**Comment by archmoj** [comment]
Thanks very much @rreusser for the quick yet another in-depth review.
I would be glad to possibly contribute more to this repo. 
So it would be nice to have the permission to work on branches.

**Comment by rreusser** [comment]
@archmoj It seems appropriate to just cut to the chase, so I've added you as an owner on the glslify github org. It looks like you have permissions on npm, so if it's alright, I'll put the ball in your court regarding merging this patch, bumping the version, and publishing to npm. Please let me know if I can help in any other way, and don't hesitate to ping me for reviews in the future, though I get busy/distracted easily, so can't make promises (though I'll do my best. ping repeatedly if necessary if I or someone else doesn't act in a timely manner 😬 ).

**Comment by archmoj** [comment]
@rreusser thanks very much.
Regarding the publishing to npm. I don't see a script to automate the processes.
So I assume I should follow the steps below:
```
npm version patch
git push
npm publish
```
Is that correct?

**Comment by rreusser** [comment]
Yes, that looks correct, I think… To be honest, I often just do it manually, so I'd write…

```
<increment version in package.json>
git add
git commit -m "vX.Y.Z"
git tag -a vX.Y.Z
git push origin
git push origin --tags
npm publish
```

Not sure if I'm missing anything there. Basically whatever gets the job done as long as it gets a patch version and a tag on github, I think.

**Comment by archmoj** [comment]
Seems there are a couple of other modules that we may want to bump before a patch release namely:
Bumping `shel-quote@1.7.2` could resolve critical vulnerability https://npmjs.com/advisories/117.
I still have difficulty running tests the second time on this repo.

**Pull request merged**
