### PR TITLE
Fix backtick usage in the README

### PR DESCRIPTION
**Pull request by parasti**

### CODE REVIEW

**Comment by mattdesl** [comment]
I seem to no longer have write access to the repo @mikolalysenko @hughsk – but this PR looks good to merge. not sure why tests are failing

**Comment by rreusser** [comment]
@mattdesl I think I've resent an invitation for you to join the glslify org as an owner. Let me know if that's not the case!

**Comment by rreusser** [comment]
Edit: not actually sure it *resent*, though it appears there is an active invitation. Maybe check https://github.com/glslify ?

**Comment by mattdesl** [comment]
Got it thanks :)

**Pull request merged**
